In [1]:
import numpy as np


In [2]:
a = np.array([3,4])
b = np.array([8,9])

In [3]:
z = np.log(a) 
print(z)

[1.09861229 1.38629436]


In [5]:
z = np.exp(a)
print(z)

[20.08553692 54.59815003]


In [6]:
z = np.sqrt(a)
print(z)

[1.73205081 2.        ]


In [8]:
z = np.dot(a,b) # inner product of vectors
print(z)
z = a.dot(b)
print(z)

60
60


In [9]:
z = np.linalg.norm(a) #to find magnitude of a
print(z)

5.0


In [10]:
cosangle = a.dot(b) / np.linalg.norm(a) * np.linalg.norm(b) #angle between two veectors.
print(cosangle)

144.49913494550754


In [12]:
a = np.matrix([[1,2,3],[4,5,6]]) #convert a matrix into array
print(a)
print(a[0,0])
x = np.array(a)
print(x)
print(x.T) #transpose

[[1 2 3]
 [4 5 6]]
1
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [13]:
z = np.zeros(5)
print(z) # 1-d array of zeros.

[0. 0. 0. 0. 0.]


In [14]:
m = np.zeros((2,2)) #5×5 matrix of zeros
print(m)



[[0. 0.]
 [0. 0.]]


In [15]:
#for 1's
o = np.ones((3,3))
print(o)

#no from random varuable b/w 0 & 1
r = np.random.random((2,2))
print(r)  

#no from gaussian distribution
#with mean 0 and variance 1
h = np.random.randn(2,2)
print(h)

#for mean and variance
print(h.mean())
print(h.var())



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.25221964 0.41678529]
 [0.68506547 0.97417113]]
[[0.60410671 0.03645504]
 [0.37645026 0.63693386]]
0.41348646904113706
0.0574472971798928


In [16]:
p = np.array([[1,2,3],[2,2,1],[6,7,9]])
q = np.array([[4,5],[6,7],[6,8]])

r = p.dot(q)
print(r)

#to find inverse
pinv = np.linalg.inv(p)
print(pinv)

# to check if inverse is correct
 #we multiply it by array
#if we get identity matrix thn right

correct = p.dot(pinv)
print(correct)



[[ 34  43]
 [ 26  32]
 [120 151]]
[[-1.57142857 -0.42857143  0.57142857]
 [ 1.71428571  1.28571429 -0.71428571]
 [-0.28571429 -0.71428571  0.28571429]]
[[ 1.00000000e+00 -3.33066907e-16  2.22044605e-16]
 [-1.66533454e-16  1.00000000e+00  2.22044605e-16]
 [ 2.77555756e-16  3.33066907e-16  1.00000000e+00]]
